project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1-1
            href: Hands-on Exercises/Hands-on_Ex1-1/Hands-on_Ex1-1.qmd
          - text: Hands-on Exercise 1-2
            href: Hands-on Exercises/Hands-on_Ex1-2/Hands-on_Ex1-2.qmd
      - text: In-class Exercises
        menu:
          - text: In-class Exercise 1
            href: In-class Exercises/In-class_Ex1/In-class_Ex1.qmd
          - text: In-class Exercise 2
      - text: Take-home Exercises
        menu:
          - text: Take-home Exercise 1
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: bootstrap
    css: styles.css
    toc: true

editor: visual

